services:
  - type: web
    name: speedjobs
    runtime: node
    plan: free
    buildCommand: bash render-build.sh
    startCommand: bash render-start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: speedjobs-db
          property: connectionString

databases:
  - name: speedjobs-db
    plan: free
